version: '3.8'

services:
  laravel_app:
    container_name: laravel_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - laravel_db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laravel_db
      DB_PORT: 3306
      DB_DATABASE: biblioteca
      DB_USERNAME: root
      DB_PASSWORD: ""
    volumes:
      - .:/var/www/html

  laravel_db:
    container_name: laravel_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"  # Evita conflicto con Laragon
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: